openapi: 3.1.1
info:
  title: API de exemplo da aplicação escola_ead
  description: Uma API de testes
  version: 0.0.1

tags:
  - Usuarios
  - Aulas
  - Certificados
  - Modulos
  - Matricula
  - Cursos

paths:
  /api/usuarios:
    $ref: './paths/Usuario/Collection.yaml'
  /api/usuarios/{id}:
    $ref: './paths/Usuario/Item.yaml'
  /api/postagens:
    $ref: './paths/Post/Collection.yaml'
  /api/postagens/{id}:
    $ref: './paths/Post/Item.yaml'

components:
  schemas:
    Usuario:
      $ref: './components/Usuario.yaml'
    Matricula:
      $ref: './components/Matricula.yaml'
    Aula:
      $ref: './components/Aula.yaml'
    Modulo:
      $ref: './components/Modulo.yaml'
    Certificado:
      $ref: './components/Certificado.yaml'
    Curso:
      $ref: './components/Curso.yaml'
